// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "produces": [
        "application/json"
    ],
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/carrier/shipment/pickup": {
            "post": {
                "description": "Carrier 取货并生成物流单，订单状态变为 READY",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Carrier"
                ],
                "summary": "承运商取货",
                "parameters": [
                    {
                        "description": "取货信息",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.PickupGoodsRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/carrier/shipment/{id}": {
            "get": {
                "description": "查询物流单的详细信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Carrier"
                ],
                "summary": "查询物流详情",
                "parameters": [
                    {
                        "type": "string",
                        "description": "物流单ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/carrier/shipment/{id}/history": {
            "get": {
                "description": "查询物流单的完整位置变更历史",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Carrier"
                ],
                "summary": "查询物流单历史记录",
                "parameters": [
                    {
                        "type": "string",
                        "description": "物流单ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/carrier/shipment/{id}/location": {
            "put": {
                "description": "Carrier 更新物流单的位置信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Carrier"
                ],
                "summary": "更新物流位置",
                "parameters": [
                    {
                        "type": "string",
                        "description": "物流单ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "位置信息",
                        "name": "location",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.UpdateLocationRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/manufacturer/order/{id}/accept": {
            "put": {
                "description": "Manufacturer 接受 OEM 创建的订单，状态变为 ACCEPTED",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Manufacturer"
                ],
                "summary": "零部件厂商接受订单",
                "parameters": [
                    {
                        "type": "string",
                        "description": "订单ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/manufacturer/order/{id}/status": {
            "put": {
                "description": "Manufacturer 更新订单的生产状态 (PRODUCING/PRODUCED/READY)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Manufacturer"
                ],
                "summary": "更新生产状态",
                "parameters": [
                    {
                        "type": "string",
                        "description": "订单ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "新状态",
                        "name": "status",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.UpdateStatusRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/oem/order/create": {
            "post": {
                "description": "OEM 创建新的采购订单，订单状态为 CREATED",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "OEM"
                ],
                "summary": "主机厂创建采购订单",
                "parameters": [
                    {
                        "description": "订单信息",
                        "name": "order",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.CreateOrderRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "订单创建成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/oem/order/list": {
            "get": {
                "description": "分页查询订单列表，支持根据角色过滤",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "OEM"
                ],
                "summary": "查询订单列表",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "每页数量",
                        "name": "pageSize",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "分页书签",
                        "name": "bookmark",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/oem/order/{id}": {
            "get": {
                "description": "根据订单ID查询订单详细信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "OEM"
                ],
                "summary": "查询订单详情",
                "parameters": [
                    {
                        "type": "string",
                        "description": "订单ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/oem/order/{id}/history": {
            "get": {
                "description": "查询订单的完整状态变更历史，展示区块链不可篡改的审计追踪",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "OEM"
                ],
                "summary": "查询订单历史记录",
                "parameters": [
                    {
                        "type": "string",
                        "description": "订单ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/oem/order/{id}/receive": {
            "put": {
                "description": "OEM 确认收货，订单状态变为 RECEIVED",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "OEM"
                ],
                "summary": "OEM 确认收货",
                "parameters": [
                    {
                        "type": "string",
                        "description": "订单ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/platform/all": {
            "get": {
                "description": "查询账本上所有资产（订单和物流单）的当前状态及其完整的历史变更记录，用于审计和追溯",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Platform"
                ],
                "summary": "查询所有账本数据及完整历史变更记录",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "每页数量",
                        "name": "pageSize",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "分页书签",
                        "name": "bookmark",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.CreateOrderRequest": {
            "type": "object"
        },
        "api.PickupGoodsRequest": {
            "type": "object",
            "required": [
                "orderId",
                "shipmentId"
            ],
            "properties": {
                "orderId": {
                    "description": "订单ID",
                    "type": "string",
                    "example": "ORDER_2024_001"
                },
                "shipmentId": {
                    "description": "物流单ID",
                    "type": "string",
                    "example": "SHIPMENT_2024_001"
                }
            }
        },
        "api.UpdateLocationRequest": {
            "type": "object",
            "required": [
                "location"
            ],
            "properties": {
                "location": {
                    "description": "当前位置",
                    "type": "string",
                    "example": "SHANGHAI_PORT"
                }
            }
        },
        "api.UpdateStatusRequest": {
            "type": "object",
            "required": [
                "status"
            ],
            "properties": {
                "status": {
                    "description": "生产状态：PRODUCING(生产中)/PRODUCED(已生产)/READY(待发货)",
                    "type": "string",
                    "enum": [
                        "PRODUCING",
                        "PRODUCED",
                        "READY"
                    ],
                    "example": "PRODUCING"
                }
            }
        },
        "utils.Response": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "message": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    },
    "tags": [
        {
            "description": "主机厂相关接口 - 订单创建、查询、签收等操作",
            "name": "OEM"
        },
        {
            "description": "零部件厂商相关接口 - 订单接受、状态更新等操作",
            "name": "Manufacturer"
        },
        {
            "description": "承运商相关接口 - 取货、物流追踪、位置更新等操作",
            "name": "Carrier"
        },
        {
            "description": "平台方相关接口 - 数据监管、审计追溯等操作",
            "name": "Platform"
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "192.168.1.41:8080",
	BasePath:         "/api",
	Schemes:          []string{"http", "https"},
	Title:            "供应链协同系统 API 文档",
	Description:      "基于 Hyperledger Fabric 的汽配供应链协同系统 API 文档\n本系统提供完整的供应链协同管理功能，包括订单管理、物流追踪、状态更新等",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
